---
version: 2
jobs:
  build:
    working_directory: ~/ncco
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: gem install bundler --pre
      - type: cache-restore
        name: Restore Bundler cache
        key: ncco-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        name: Save Bundler cache
        key: ncco-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: bundle exec rake
      - run: bundle exec rake lint